### ISSUE TITLE
TestPacketContentAssemblerFlowsAndFiles not executable in StreamsStudio

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#91] opened 2017-01-30 10:32 UTC
The sample TestPacketContentAssemblerFlowsAndFiles cannot be executed successfully in StreamsStudio. During execution a signal SIGSEGV, Segmentation fault, occurs and the resulting output files 'debug.*' are empty. Attached is the error output.

[Result_Studio__standalone_execution_V3.0.0.TXT](https://github.com/IBMStreams/streamsx.network/files/738588/Result_Studio__standalone_execution_V3.0.0.TXT)

The problem is that the subdirectories of the data directory do not yet exist when the custom operators want to write into it.

**Comment by ejpring** [comment] 2017-01-30 12:18
I think this exception is caused by this code:

        mutable int32 error = 0;
        uint64 handle = fopen(filename, filemode, error);
        assert(error==0, "Sorry, could not open output file '" + filename + "', " + strerror(error));
        fwriteString(string, handle, error);
        assert(error==0, "Sorry, could not write output file '" + filename + "', " + strerror(error));

The assert() function following fopen() should catch this error if you compile without SPL optimization. If you compile with SPL optimization, the assert() function is ignored. I think that was a poor design choice, and I'd be happy to see it changed.

However, I think we can all agree that fwriteString() should return an error code in this situation instead of throwing an uncaught exception. Please open a defect against the runtime SPL library.

It might also be worth asking the Studio folks to create a 'data' directory when running an application that does not have one, for backwards compatibility.

**Comment by markheger** [comment] 2017-01-30 12:34
The sample SPL code needs to be fixed to create the required sub directory in SPL instead of rely that the directory exists or to create it in test-scripts only.

  () as FlowDataStore = Custom(FlowDataStream as In) {
    logic state: {
      mutable boolean res=createDir(dataDirectory() + "/debug.TestPacketContentAssemblerFlowsAndFiles");

In Functions.spl:
/**
 * It creates a directory by path name
 * @param path The directory path
 * @return `true` if created else `false`
 */
public stateful boolean createDir(rstring path) {
  mutable boolean result = true;
  mutable int32 errorCode = 0;
  spl.file::mkdir(path, 999u, errorCode);
  if (errorCode != 0) {
    result = false;
  }
  return result;
}

**Comment by markheger** [comment] 2017-01-30 12:38
@ejpring Please review the pull request above

**Comment by ejpring** [comment] 2017-01-30 13:17
I don't think this toolkit's sample applications should cover up a bug in the SPL::File::fwriteString() function. The sample applications should log an error if fwriteString() fails, not throw an uncaught addressing exception. Let's get the bug fixed.

**Comment by markheger** [comment] 2017-01-30 13:52
I agree that there might be a bug in fwriteString(), that could be fixed.
Nevertheless the sample is currently very user-unfriendly for usage in StreamsStudio.
It is not documented that the user has to create a directory manually. In current and older Streams releases the user would never get a proper hint because the signal is raised.
In the test script you create a directory that is required by an operator in the sample application and you cover up the bug with this workaround.
The proper way would be that the sample application works without any manual directory creation by the user since it is possible to create directories in Streams operators with spl.file::mkdir method.

**Comment by ejpring** [comment] 2017-01-30 14:07
I agree that the product's decision to eliminate the 'data' directory is not user-friendly and not backwards-compatible, but was the decision.

I also agree that this toolkit's documentation should tell Studio users to create a 'data' directory manually before running the sample applications. If they don't, the sample applications should log an error message that says the directory does not exist. The sample applications should not create a 'data' directory. 

In any case, the uncaught address exception is a bug and it needs to be fixed. It could be fixed by catching the exception in fwriteString() and returning an error code. Or, it could be fixed in fopen() by creating the file's directory if it does not exist. That would be a good discussion to have with the product developers. Please open a defect against the SPL runtime library to start that discussion.

**Comment by markheger** [comment] 2017-01-30 14:48
Studio creates the data directory during "build job".
The code changes proposed are solving the problem that the missing sub directory ("debug.TestPacketContentAssemblerFlowsAndFiles") is created automatically and the sample application would work in StreamsStudio and test script in the same way.

**Comment by ejpring** [comment] 2017-02-01 01:55
Please pull today's changes from the fork at https://github.com/ejpring/streamsx.network and retest ...

**Comment by markheger** [comment] 2017-02-01 08:24
@ejpring I have seen your commits in your fork. The sample TestPacketContentAssemblerFlowsAndFiles.spl works without the need of the additional sub directory. All files are written into data directory now. This is not very beautiful but solves the problem.
You missed to change LivePacketContentAssemblerFlowsAndFiles.spl and livePacketContentAssemblerFlowsAndFiles.sh.

**Comment by GudrunKa** [comment] 2017-02-01 13:14
Why not creating the sub directory of the data directory in the way Mark proposed? In this way the output files would be clearly arranged and assigned to a sample (as they were before), and it makes it easier to check what output files were generated.
If you put the debug.flow* files into the data directory where also the output files of the other samples are written, it is hard to separate them.

By the way: Would it not be useful to distinguish the generated output files of the two custom operators by name?

() as FlowDataStore = Custom(**Flow**DataStream as In) {
...
onTuple In: {
      rstring filename = dataDirectory() + "/debug.TestPacketContentAssemblerFlowsAndFiles/debug.**flow_**" + ...;

() as FileChunkStore = Custom(**File**ChunkStream as In) {
    logic onTuple In: {
      rstring filename = dataDirectory() + "/debug.TestPacketContentAssemblerFlowsAndFiles/debug.**file_**" +  ...;

**Comment by ejpring** [comment] 2017-02-01 13:47
In the samples, the filenames for reassembled files include both flow and file identifiers to show which flows the files were reassembled from. Their purpose is to illustrate the PacketContentAssembler operator. The Custom operators are just simple examples of how its data and metadata might be used.

**Comment by GudrunKa** [comment] 2017-02-01 14:07
Yes, I see. It does not make sense when I see the whole file name.

And what about my first question:
Why not creating the sub directory of the data directory in the way Mark proposed? In this way the output files would be clearly arranged and assigned to a sample (as they were before), and it makes it easier to check what output files were generated.
If you put the debug.flow* files into the data directory where also the output files of the other samples are written, it is hard to separate them.

**Comment by ejpring** [comment] 2017-02-01 15:01
Thanks for verifying the changes to the PacketContentAssembler samples. No one has ever accused the samples of being beautiful. If they give customers a head start on building real applications, they've done their job.

**Closed as completed** 2017-02-09 12:36 UTC
